// Copyright (c) Zhongkai Fu. All rights reserved.
// https://github.com/zhongkaifu/TensorSharp
//
// This file is part of TensorSharp.
//
// TensorSharp is licensed under the BSD-3-Clause license found in the LICENSE file in the root directory of this source tree.
//
// TensorSharp is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the BSD-3-Clause License for more details.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Numerics.Tensors;
using System.Threading;
using System.Threading.Tasks;

namespace TensorSharp.Models
{
    /// <summary>Hyper-parameters for the DiffusionGemma EntropyBound denoising sampler.
    /// Defaults mirror the reference (llama.cpp diffusion-gemma) values.</summary>
    public sealed class DiffusionEbParams
    {
        public int MaxDenoisingSteps = 48;
        public float TMin = 0.4f;            // temperature at the last step
        public float TMax = 0.8f;            // temperature at the first step
        public float EntropyBound = 0.1f;    // accept lowest-entropy tokens within this MI bound
        public int StabilityThreshold = 1;   // # of steps the argmax canvas must hold to count stable
        public float ConfidenceThreshold = 0.005f; // stop once mean canvas entropy drops below this
        public int Seed = 0;
        public int MaxBlocks = 1;            // block-autoregressive blocks (each = canvas_length tokens)

        // --- Structured reads (see DiffusionReadOptions) ---

        /// <summary>Token ids that replace the random initial canvas of the first block, exactly
        /// <see cref="CanvasWidth"/> long. Null keeps the random canvas.</summary>
        public int[] SeedCanvas = null;

        /// <summary>The leading canvas positions this request owns; 0 means the whole served canvas.
        /// The model forward is fixed-width, so the tail beyond this is still denoised - it is simply
        /// not part of the request's canvas, and neither converges it nor is emitted.</summary>
        public int CanvasWidth = 0;

        /// <summary>Emit the argmax canvas as soon as the step cap (or convergence) is reached and end
        /// there: one canvas is the whole output, with no end-of-turn trimming.</summary>
        public bool ReadOnly = false;

        /// <summary>Top tokens to report per canvas position, at temperature 1. Read-only only.</summary>
        public int TopLogprobs = 0;
    }

    /// <summary>
    /// The DiffusionGemma "EntropyBound" denoising sampler.
    ///
    /// Each block of <c>canvas_length</c> tokens is generated by iterative denoising:
    ///  - The canvas is initialized with random tokens (NOT a mask token).
    ///  - Each step runs a bidirectional forward and, per canvas position, computes the argmax,
    ///    the Shannon entropy of softmax(logits/t), and one multinomial sample.
    ///  - The lowest-entropy positions (cumulative mutual-information &lt;= entropy_bound) are accepted
    ///    (kept = sampled token); the rest are re-noised with fresh random tokens.
    ///  - The emitted/output canvas is always the deterministic argmax canvas.
    ///  - Generation stops early when the argmax canvas is stable for <c>StabilityThreshold</c> steps
    ///    and the mean entropy is below <c>ConfidenceThreshold</c>.
    ///
    /// Multiple blocks are generated autoregressively: a finished block is committed to the prompt
    /// prefix and the next block is denoised, until an end-of-generation token or a repetition loop.
    /// </summary>
    public sealed class DiffusionGemmaSampler
    {
        private readonly DiffusionGemmaModel _model;
        private readonly int _vocab;
        private readonly int _canvasLength;

        // How to decode concurrent requests' canvases each step:
        //  - default (false): run the fast FUSED single-canvas kernel once per live sequence (time-slice).
        //    On a GPU already compute-saturated by one canvas (the case for this 128-expert MoE at
        //    canvas=256), this is the fastest aggregate path — the fused kernel is ~3x faster per canvas
        //    than the per-op true-batched forward, and true batching can't beat a compute-bound GPU.
        //  - DIFFUSION_BATCHED_FORWARD=1: fuse all live canvases into ONE per-op batched forward
        //    (DecodeCanvasBatched). Correct, and a win only when a single canvas leaves the GPU
        //    under-utilised (small canvas / large GPU); a loss when already compute-bound.
        private readonly bool _useBatchedForward = Environment.GetEnvironmentVariable("DIFFUSION_BATCHED_FORWARD") == "1";

        // One-time notice when the on-device sampling kernel rejects a step and the
        // block continues on the host logits path (full [vocab,C] logits cross PCIe
        // plus a host CPU sweep per step — slower).
        private bool _deviceSampleFallbackWarned;

        private void WarnDeviceSampleFallback()
        {
            if (_deviceSampleFallbackWarned) return;
            _deviceSampleFallbackWarned = true;
            Console.WriteLine("  [device-sample] on-device sampling kernel rejected the layout; " +
                "sampling moves to the host logits path for the rest of the block (full logits readback " +
                "per step, slower). Reported once.");
        }

        public DiffusionGemmaSampler(DiffusionGemmaModel model)
        {
            _model = model;
            _vocab = model.VocabSize;
            _canvasLength = model.CanvasLength;
        }

        /// <summary>Generate a full response (block-autoregressive) for the given prompt tokens.
        /// <paramref name="blockStepCallback"/> is invoked after every denoising step with
        /// (blockIndex, step, totalSteps, previewTokens) where previewTokens is the committed
        /// response so far plus the current block's best-guess (argmax) canvas — useful for a live
        /// "denoising" preview in a UI. <paramref name="ct"/> stops generation between steps.</summary>
        public List<int> Generate(int[] promptTokens, DiffusionEbParams p,
            Action<int, int, int, int[]> blockStepCallback = null,
            CancellationToken ct = default)
        {
            var prefix = new List<int>(promptTokens);
            var response = new List<int>();

            int blocks = Math.Max(1, p.MaxBlocks);
            for (int b = 0; b < blocks; b++)
            {
                if (ct.IsCancellationRequested) break;
                int bIdx = b;
                // A seed canvas describes the answer being read, so it belongs to the first block only;
                // later blocks continue from the committed prefix on a random canvas as usual.
                int[] canvas = DenoiseBlockCore(prefix.ToArray(), p, applySeed: b == 0,
                    blockStepCallback == null ? null : (step, total, argmax) =>
                    {
                        var preview = new int[response.Count + argmax.Length];
                        response.CopyTo(preview, 0);
                        argmax.CopyTo(preview, response.Count);
                        blockStepCallback(bIdx, step, total, preview);
                    },
                    ct).Canvas;

                int cut = TrimCanvas(canvas, canvas.Length);
                for (int i = 0; i < cut; i++) response.Add(canvas[i]);

                if (cut < canvas.Length) break;            // end token or repetition loop -> done
                for (int i = 0; i < cut; i++) prefix.Add(canvas[i]);
            }
            return response;
        }

        /// <summary>The canvas positions a request owns: its own width, else the served canvas.</summary>
        private int WidthOf(DiffusionEbParams p) =>
            p.CanvasWidth > 0 ? Math.Min(p.CanvasWidth, _canvasLength) : _canvasLength;

        /// <summary>Denoise a single block of <c>canvas_length</c> tokens. Returns the argmax canvas.
        /// <paramref name="stepCallback"/> receives (step, totalSteps, argmaxCanvasSnapshot) each step.</summary>
        public int[] DenoiseBlock(int[] promptTokens, DiffusionEbParams p,
            Action<int, int, int[]> stepCallback = null, CancellationToken ct = default)
            => DenoiseBlockCore(promptTokens, p, applySeed: true, stepCallback, ct).Canvas;

        /// <summary>
        /// Perform a structured read: denoise the seeded canvas for at most
        /// <see cref="DiffusionEbParams.MaxDenoisingSteps"/> steps and return the canvas the model settled
        /// on, untrimmed, together with the temperature-1 distribution at every position when
        /// <see cref="DiffusionEbParams.TopLogprobs"/> asks for one. The canvas IS the answer, so nothing
        /// is cut at an end-of-turn token and no second block is generated.
        /// </summary>
        public DiffusionReadResult Read(int[] promptTokens, DiffusionEbParams p,
            Action<int, int, int[]> stepCallback = null, CancellationToken ct = default)
        {
            if (p == null) throw new ArgumentNullException(nameof(p));
            if (!p.ReadOnly)
                throw new ArgumentException("A read needs DiffusionEbParams.ReadOnly set.", nameof(p));
            return DenoiseBlockCore(promptTokens, p, applySeed: true, stepCallback, ct);
        }

        /// <summary>Denoise one block and report everything a structured read needs: the emitted canvas,
        /// the steps it took, whether it converged, and - for a read asking for them - the temperature-1
        /// distributions of the step that emitted.</summary>
        private DiffusionReadResult DenoiseBlockCore(int[] promptTokens, DiffusionEbParams p, bool applySeed,
            Action<int, int, int[]> stepCallback, CancellationToken ct)
        {
            int P = promptTokens.Length;
            int C = _canvasLength;
            int W = WidthOf(p);
            int S = Math.Max(1, p.MaxDenoisingSteps);
            int vocab = _vocab;

            var rng = new DeterministicRng((ulong)p.Seed);

            int[] currentCanvas = new int[C];
            for (int i = 0; i < C; i++) currentCanvas[i] = rng.NextInt(vocab);
            if (applySeed) ApplySeedCanvas(p, currentCanvas, W);

            // Self-conditioning reads the PREVIOUS step's logits. The model reads scBuffer at the START of
            // the forward (before it overwrites/produces the new logits), so we can hand it the previous
            // step's returned logits array directly instead of copying 268 MB into a side buffer each step.
            // Both paths return a reusable buffer (fused: _fusedLogitsBuffer, per-op: _canvasLogits) that
            // is only overwritten at the END of the forward — after SC has read it — so the alias is safe.
            float[] scBuffer = null;
            int[] argmaxCanvas = new int[W];
            int[] prevArgmax = new int[W];
            for (int i = 0; i < W; i++) prevArgmax[i] = -1;

            float[] entropy = new float[C];
            int[] denoiser = new int[C];
            int[] order = new int[C];
            float[] u = new float[C];
            int[] renoise = new int[C];

            // Prompt-KV caching: prefill the prompt's per-layer K/V once, then each step decodes only the
            // canvas (reading the cached prompt K/V). Falls back to the unified [prompt|canvas] forward.
            bool usePkv = _model.SupportsPromptKvCache;
            int[] tokens = null;
            if (usePkv)
            {
                _model.PrefillPrompt(promptTokens);
            }
            else
            {
                tokens = new int[P + C];
                Array.Copy(promptTokens, tokens, P);
            }

            // A read reports the distribution itself, which only the full logits carry. The on-device
            // sampler returns a top-K taken at the step's temperature, so such a request stays on the host
            // logits path - one readback per step, over the handful of steps a read runs.
            bool wantLogprobs = p.ReadOnly && p.TopLogprobs > 0;

            // On-device sampling (CUDA): the lm_head kernel returns argmax/entropy/sampled/top-K directly,
            // so the full [vocab,C] logits never cross PCIe and no host full-vocab CPU sweep runs. Needs the
            // prompt-KV decode path (its canvas hidden stays on-device for the sampling tail). The per-step
            // top-K (double-buffered) feeds the NEXT step's self-conditioning, replacing the host logits.
            bool useDeviceSample = usePkv && _model.SupportsDeviceSampling && !wantLogprobs;
            int K = _model.SelfCondTopK;
            int[] dArg = null, dSamp = null;
            int[][] topTok = null; float[][] topPrb = null; int dbuf = 0;
            if (useDeviceSample)
            {
                dArg = new int[C]; dSamp = new int[C];
                int kk = Math.Max(1, K);
                topTok = new[] { new int[C * kk], new int[C * kk] };
                topPrb = new[] { new float[C * kk], new float[C * kk] };
            }

            float prevTempInv = 1f;
            int held = 0;
            bool finished = false;
            int stepsRun = 0;
            DiffusionPositionLogprobs[] logprobs = null;

            for (int curStep = S; curStep >= 1 && !finished && !ct.IsCancellationRequested; curStep--)
            {
                int stepIdx = S - curStep;
                float t = p.TMin + (p.TMax - p.TMin) * ((float)curStep / S);
                float tempInv = 1f / t;
                float scUse = stepIdx == 0 ? 0f : 1f;

                if (useDeviceSample)
                {
                    // pre-draw step randomness (u then renoise per position) so the rng order matches the
                    // host sampler; u drives the on-device multinomial, renoise the rejected positions.
                    for (int pos = 0; pos < C; pos++) { u[pos] = rng.NextFloat(); renoise[pos] = rng.NextInt(vocab); }
                    int[] scTok = stepIdx == 0 ? null : topTok[1 - dbuf];
                    float[] scPrb = stepIdx == 0 ? null : topPrb[1 - dbuf];
                    bool ok = _model.DecodeCanvasSampled(currentCanvas, scTok, scPrb, scUse, tempInv, u, K,
                        dArg, entropy, dSamp, topTok[dbuf], topPrb[dbuf]);
                    if (ok)
                    {
                        finished = DenoiseStepFromDevice(dArg, entropy, dSamp, renoise, p,
                            currentCanvas, argmaxCanvas, prevArgmax, ref held, order, W);
                        dbuf ^= 1;
                        prevTempInv = tempInv;
                        stepsRun++;
                        stepCallback?.Invoke(stepIdx, S, (int[])argmaxCanvas.Clone());
                        continue;
                    }
                    // device path rejected the layout: fall back to the host logits path for the rest of the
                    // block (self-conditioning restarts from the next step, scBuffer null this step).
                    useDeviceSample = false;
                    WarnDeviceSampleFallback();
                }

                float[] logits;
                if (usePkv)
                {
                    logits = _model.DecodeCanvas(currentCanvas, scBuffer, scUse, prevTempInv);
                }
                else
                {
                    for (int i = 0; i < C; i++) tokens[P + i] = currentCanvas[i];
                    logits = _model.ForwardCanvas(tokens, P, scBuffer, scUse, prevTempInv);
                }

                // per-position sampling + accept + renoise + adaptive-stop (shared with the batched path)
                finished = DenoiseStep(logits, tempInv, rng, p, currentCanvas, argmaxCanvas, prevArgmax,
                    ref held, entropy, denoiser, order, u, renoise, W);
                prevTempInv = tempInv;
                stepsRun++;

                // Only the step that emits is reported, so the top-K sweep runs once per read rather than
                // once per step. These logits are still this step's; the next forward overwrites them.
                if (wantLogprobs && (finished || curStep == 1))
                    logprobs = DiffusionLogprobs.TopKPerPosition(logits, W, vocab, p.TopLogprobs);

                // hand this step's logits to the next step's self-conditioning (no copy; see scBuffer note)
                if (_model.SelfConditioningEnabled) scBuffer = logits;

                stepCallback?.Invoke(stepIdx, S, (int[])argmaxCanvas.Clone());
            }

            return new DiffusionReadResult((int[])argmaxCanvas.Clone(), logprobs, stepsRun, finished);
        }

        /// <summary>Overwrite the request's canvas positions with its seed ids. The tail past
        /// <paramref name="width"/> keeps its noise: it is outside the request's canvas.</summary>
        private static void ApplySeedCanvas(DiffusionEbParams p, int[] canvas, int width)
        {
            int[] seed = p.SeedCanvas;
            if (seed == null) return;
            if (seed.Length != width)
                throw new ArgumentException(
                    $"SeedCanvas must hold exactly {width} ids, got {seed.Length}.", nameof(p));
            Array.Copy(seed, canvas, width);
        }

        /// <summary>One denoising step's host-side work, shared by the single-request <see cref="DenoiseBlock"/>
        /// and the batched <see cref="RunBlockBatched"/> paths so they are numerically identical: per canvas
        /// position compute argmax + Shannon entropy of softmax(logits*tempInv) + one multinomial sample,
        /// accept the lowest-entropy positions within the MI bound (kept = sampled token, rest = fresh random),
        /// and report the adaptive-stop verdict (argmax stable for StabilityThreshold steps AND mean entropy
        /// below ConfidenceThreshold). Updates <paramref name="currentCanvas"/> (next step's input),
        /// <paramref name="argmaxCanvas"/> (the emitted best-guess), <paramref name="prevArgmax"/> and
        /// <paramref name="held"/>. The scratch arrays are caller-owned to keep the hot loop allocation-light.</summary>
        private bool DenoiseStep(float[] logits, float tempInv, DeterministicRng rng, DiffusionEbParams p,
            int[] currentCanvas, int[] argmaxCanvas, int[] prevArgmax, ref int held,
            float[] entropy, int[] denoiser, int[] order, float[] u, int[] renoise, int width)
        {
            int C = _canvasLength;
            int W = width;
            int vocab = _vocab;

            // pre-draw step randomness (single-threaded) for reproducibility
            for (int pos = 0; pos < C; pos++)
            {
                u[pos] = rng.NextFloat();
                renoise[pos] = rng.NextInt(vocab);
            }

            // per position: argmax + entropy of softmax(logits*tempInv) + one multinomial sample.
            // SIMD-vectorized via TensorPrimitives (exp/sum/dot), with per-worker scratch rows:
            //   s = logits*tempInv;  e = exp(s - max(s));  Z = Σe
            //   H = -Σ p ln p  with  p = e/Z  and  ln p = (s - m) - ln Z
            //     = ln Z + m - (Σ e·s)/Z
            //   sample = first v with cumulative Σe >= u*Z (the same CDF-inverse draw as the scalar
            //   reference, over the same token ordering).
            Parallel.For(0, W,
                () => (scaled: new float[vocab], exps: new float[vocab]),
                (pos, _, scratch) =>
                {
                    var row = logits.AsSpan(pos * vocab, vocab);
                    var s = scratch.scaled.AsSpan();
                    var e = scratch.exps.AsSpan();
                    TensorPrimitives.Multiply(row, tempInv, s);
                    int amax = TensorPrimitives.IndexOfMax<float>(s);
                    float m = s[amax];
                    TensorPrimitives.Subtract(s, m, e);
                    TensorPrimitives.Exp(e, e);
                    float Z = TensorPrimitives.Sum<float>(e);
                    float sz = TensorPrimitives.Dot<float>(e, s);
                    entropy[pos] = MathF.Log(Z) + m - sz / Z;

                    float target = u[pos] * Z;
                    float cum = 0f;
                    int sampled = vocab - 1;
                    for (int v = 0; v < vocab; v++)
                    {
                        cum += e[v];
                        if (cum >= target) { sampled = v; break; }
                    }
                    argmaxCanvas[pos] = amax;
                    denoiser[pos] = sampled;
                    return scratch;
                },
                _ => { });

            var accepted = AcceptLowestEntropy(entropy, order, W, p.EntropyBound);

            // renoise: accepted -> sampled token, rest -> fresh random; output = argmax canvas
            float entropySum = 0f;
            for (int pos = 0; pos < W; pos++)
            {
                currentCanvas[pos] = accepted[pos] ? denoiser[pos] : renoise[pos];
                entropySum += entropy[pos];
            }
            // Positions past the request's canvas are not its answer: they stay noise so nothing the model
            // writes there can settle and read back as content.
            for (int pos = W; pos < C; pos++) currentCanvas[pos] = renoise[pos];

            return AdaptiveStop(argmaxCanvas, prevArgmax, ref held, entropySum, W, p);
        }

        /// <summary>Accept the lowest-entropy canvas positions whose cumulative mutual information stays
        /// within <paramref name="entropyBound"/> (the sum of strictly-earlier entropies).</summary>
        private static bool[] AcceptLowestEntropy(float[] entropy, int[] order, int width, float entropyBound)
        {
            for (int i = 0; i < width; i++) order[i] = i;
            Array.Sort(order, 0, width, Comparer<int>.Create((a, b) => entropy[a].CompareTo(entropy[b])));
            var accepted = new bool[width];
            double cumE = 0.0;
            for (int k = 0; k < width; k++)
            {
                int pos = order[k];
                cumE += entropy[pos];
                if (cumE - entropy[pos] <= entropyBound) accepted[pos] = true;
            }
            return accepted;
        }

        /// <summary>The adaptive stop: the argmax canvas has held for StabilityThreshold steps AND the mean
        /// entropy over the request's canvas is below ConfidenceThreshold.</summary>
        private static bool AdaptiveStop(int[] argmaxCanvas, int[] prevArgmax, ref int held, float entropySum,
            int width, DiffusionEbParams p)
        {
            bool same = true;
            for (int i = 0; i < width; i++) if (prevArgmax[i] != argmaxCanvas[i]) { same = false; break; }
            held = same ? held + 1 : 0;
            bool confident = (entropySum / width) < p.ConfidenceThreshold;
            Array.Copy(argmaxCanvas, prevArgmax, width);
            return held >= p.StabilityThreshold && confident;
        }

        /// <summary>The host half of a denoising step when the per-position argmax/entropy/multinomial sample
        /// were computed ON-DEVICE (the GPU sampler). Identical accept/renoise/adaptive-stop logic to the back
        /// half of <see cref="DenoiseStep"/> — only the full-vocab per-position work is gone (done in the
        /// kernel). <paramref name="argmaxIn"/>/<paramref name="entropyIn"/>/<paramref name="sampledIn"/> are
        /// the device outputs; <paramref name="renoise"/> the host-drawn fresh tokens for rejected positions.</summary>
        private bool DenoiseStepFromDevice(int[] argmaxIn, float[] entropyIn, int[] sampledIn, int[] renoise,
            DiffusionEbParams p, int[] currentCanvas, int[] argmaxCanvas, int[] prevArgmax, ref int held,
            int[] order, int width)
        {
            int C = _canvasLength;
            int W = width;
            Array.Copy(argmaxIn, argmaxCanvas, W);   // emitted best-guess = device argmax

            var accepted = AcceptLowestEntropy(entropyIn, order, W, p.EntropyBound);

            // renoise: accepted -> device multinomial sample, rest -> fresh random; output = argmax canvas
            float entropySum = 0f;
            for (int pos = 0; pos < W; pos++)
            {
                currentCanvas[pos] = accepted[pos] ? sampledIn[pos] : renoise[pos];
                entropySum += entropyIn[pos];
            }
            for (int pos = W; pos < C; pos++) currentCanvas[pos] = renoise[pos];

            return AdaptiveStop(argmaxCanvas, prevArgmax, ref held, entropySum, W, p);
        }

        // ===================================================================================
        //  Batched (multi-request) generation — the parallel-request throughput path.
        //  The server scheduler keeps a set of in-flight requests as DiffusionSeqRun objects and drives
        //  them one BLOCK at a time via RunBlockBatched, which prefills every active prompt then denoises
        //  all canvases together (one batched model forward per step). Sequences converge / end / hit their
        //  block budget independently; the scheduler admits new requests and retires finished ones between
        //  blocks (block-granular continuous batching).
        // ===================================================================================

        /// <summary>Run ONE block of denoising over every active sequence in lockstep. Prefills each
        /// sequence's current prefix, denoises all canvases together (batched forward per step), and commits
        /// each sequence's trimmed block tokens via <see cref="DiffusionSeqRun.CommitBlock"/>. A sequence that
        /// converges early (or whose request is cancelled) freezes its canvas and is dropped from the batch
        /// for the remaining steps so it doesn't waste GPU work on the slower sequences.</summary>
        public void RunBlockBatched(IReadOnlyList<DiffusionSeqRun> active, CancellationToken stopToken = default)
        {
            int A = active.Count;
            if (A == 0) return;
            int C = _canvasLength;
            int vocab = _vocab;

            var seqs = new DiffusionSeqState[A];
            var canvas = new int[A][];
            var argmaxCanvas = new int[A][];
            var prevArgmax = new int[A][];
            var scBuffer = new float[A][];
            var rng = new DeterministicRng[A];
            var held = new int[A];
            var finished = new bool[A];
            // finished[] also retires a sequence that has spent its own steps, so convergence - which a
            // read reports - is tracked apart from it.
            var converged = new bool[A];
            var prevTempInv = new float[A];
            // Per-request canvas width and structured-read bookkeeping. A read reports the distribution
            // itself, which only the full logits carry, so it stays on the host logits path.
            var width = new int[A];
            var wantLogprobs = new bool[A];
            var logprobs = new DiffusionPositionLogprobs[A][];
            var stepsRun = new int[A];
            for (int a = 0; a < A; a++)
            {
                width[a] = WidthOf(active[a].Params);
                wantLogprobs[a] = active[a].Params.ReadOnly && active[a].Params.TopLogprobs > 0;
            }
            int Smax = 1;

            // Prompt-KV caching (device-glue backends): prefill each sequence's prefix K/V once, then each
            // step decodes only its canvas. CPU backends have no prompt-KV store, so each step runs the
            // unified [prefix|canvas] forward per sequence instead — the same fallback DenoiseBlock uses.
            bool usePkv = _model.SupportsPromptKvCache;
            var unifiedTokens = usePkv ? null : new int[A][];   // per-seq [prefix|canvas] buffer
            var promptLen = usePkv ? null : new int[A];

            // On-device sampling (CUDA, model fits): per-sequence the lm_head kernel returns argmax/entropy/
            // sampled/top-K directly, so no full [vocab,C] logits cross PCIe. Each sequence keeps its own
            // double-buffered top-K (for self-conditioning), argmax/sampled, mirroring DenoiseBlock.
            bool useDeviceSample = usePkv && _model.SupportsDeviceSampling && Array.TrueForAll(wantLogprobs, w => !w);
            int K = _model.SelfCondTopK;
            int[][][] dTopTok = useDeviceSample ? new int[A][][] : null;
            float[][][] dTopPrb = useDeviceSample ? new float[A][][] : null;
            int[] dBuf = useDeviceSample ? new int[A] : null;
            int[][] dArg = useDeviceSample ? new int[A][] : null;
            int[][] dSamp = useDeviceSample ? new int[A][] : null;

            // per-sequence prefill + block init
            for (int a = 0; a < A; a++)
            {
                var run = active[a];
                seqs[a] = run.State;
                if (usePkv)
                {
                    _model.PrefillSeq(run.State, run.Prefix.ToArray());
                }
                else
                {
                    int P = run.Prefix.Count;
                    promptLen[a] = P;
                    unifiedTokens[a] = new int[P + C];
                    run.Prefix.CopyTo(unifiedTokens[a], 0);
                }

                int S = Math.Max(1, run.Params.MaxDenoisingSteps);
                if (S > Smax) Smax = S;
                rng[a] = new DeterministicRng((ulong)run.Params.Seed);
                canvas[a] = new int[C];
                for (int i = 0; i < C; i++) canvas[a][i] = rng[a].NextInt(vocab);
                // A seed canvas describes the answer being read, so it seeds the first block only.
                if (run.BlockIndex == 0) ApplySeedCanvas(run.Params, canvas[a], width[a]);
                argmaxCanvas[a] = new int[width[a]];
                prevArgmax[a] = new int[width[a]];
                for (int i = 0; i < width[a]; i++) prevArgmax[a][i] = -1;
                // device sampling carries SC via the top-K buffers, so the 268 MB host logits buffer is unused
                scBuffer[a] = (_model.SelfConditioningEnabled && !useDeviceSample) ? new float[(long)C * vocab] : null;
                prevTempInv[a] = 1f;
                if (useDeviceSample)
                {
                    int kk = Math.Max(1, K);
                    dTopTok[a] = new[] { new int[C * kk], new int[C * kk] };
                    dTopPrb[a] = new[] { new float[C * kk], new float[C * kk] };
                    dArg[a] = new int[C];
                    dSamp[a] = new int[C];
                }
            }

            // caller-owned per-step scratch (one set; the per-position work is over a single canvas at a time)
            float[] entropy = new float[C];
            int[] denoiser = new int[C];
            int[] order = new int[C];
            float[] u = new float[C];
            int[] renoise = new int[C];

            // indices of sequences still denoising this block
            var live = new List<int>(A);
            for (int a = 0; a < A; a++) live.Add(a);

            for (int stepIdx = 0; stepIdx < Smax && live.Count > 0 && !stopToken.IsCancellationRequested; stepIdx++)
            {
                // drop cancelled requests from the live set before computing
                for (int j = live.Count - 1; j >= 0; j--)
                {
                    int a = live[j];
                    if (active[a].Ct.IsCancellationRequested) { finished[a] = true; live.RemoveAt(j); }
                }
                int L = live.Count;
                if (L == 0) break;

                if (_useBatchedForward && usePkv && L > 1)
                {
                    // EXPERIMENTAL true-batched forward: all live canvases through one per-op forward. A win
                    // only when a single canvas under-utilises the GPU; a loss when compute-bound (this model).
                    var subSeqs = new DiffusionSeqState[L];
                    var subCanvas = new int[L][];
                    var subScPrev = new float[L][];
                    var subScUse = new float[L];
                    var subPrevTempInv = new float[L];
                    var subTempInv = new float[L];
                    for (int j = 0; j < L; j++)
                    {
                        int a = live[j];
                        var run = active[a];
                        int S = Math.Max(1, run.Params.MaxDenoisingSteps);
                        int curStep = S - stepIdx;
                        subTempInv[j] = 1f / (run.Params.TMin + (run.Params.TMax - run.Params.TMin) * ((float)curStep / S));
                        subScUse[j] = stepIdx == 0 ? 0f : 1f;
                        subScPrev[j] = scBuffer[a];
                        subSeqs[j] = seqs[a];
                        subCanvas[j] = canvas[a];
                        subPrevTempInv[j] = prevTempInv[a];
                    }
                    float[][] logits = _model.DecodeCanvasBatched(subSeqs, subCanvas, subScPrev, subScUse, subPrevTempInv);
                    for (int j = 0; j < L; j++)
                    {
                        int a = live[j];
                        var run = active[a];
                        if (scBuffer[a] != null) Array.Copy(logits[j], scBuffer[a], (long)C * vocab);
                        int Sa = Math.Max(1, run.Params.MaxDenoisingSteps);
                        bool seqFinished = DenoiseStep(logits[j], subTempInv[j], rng[a], run.Params,
                            canvas[a], argmaxCanvas[a], prevArgmax[a], ref held[a], entropy, denoiser, order, u,
                            renoise, width[a]);
                        prevTempInv[a] = subTempInv[j];
                        stepsRun[a]++;
                        if (wantLogprobs[a] && (seqFinished || stepsRun[a] >= Sa))
                            logprobs[a] = DiffusionLogprobs.TopKPerPosition(
                                logits[j], width[a], vocab, run.Params.TopLogprobs);
                        run.EmitPreview(stepIdx, Sa, argmaxCanvas[a]);
                        if (seqFinished) { finished[a] = true; converged[a] = true; }
                    }
                }
                else
                {
                    // DEFAULT: decode each live sequence with the fast FUSED single-canvas kernel, then sample
                    // immediately (the kernel returns the model's shared readback buffer, so its logits must be
                    // consumed before the next sequence's decode overwrites it). Time-slices the GPU across the
                    // active requests at full fused speed. Without prompt-KV (CPU backends) each sequence runs
                    // the unified [prefix|canvas] forward instead, which has the same shared-buffer contract.
                    for (int j = 0; j < L; j++)
                    {
                        int a = live[j];
                        var run = active[a];
                        int S = Math.Max(1, run.Params.MaxDenoisingSteps);
                        int curStep = S - stepIdx;                  // mirrors single-seq: curStep counts S..1
                        float tempInv = 1f / (run.Params.TMin + (run.Params.TMax - run.Params.TMin) * ((float)curStep / S));
                        float scUse = stepIdx == 0 ? 0f : 1f;

                        if (useDeviceSample)
                        {
                            for (int pos = 0; pos < C; pos++) { u[pos] = rng[a].NextFloat(); renoise[pos] = rng[a].NextInt(vocab); }
                            int[] scTok = stepIdx == 0 ? null : dTopTok[a][1 - dBuf[a]];
                            float[] scPrb = stepIdx == 0 ? null : dTopPrb[a][1 - dBuf[a]];
                            bool ok = _model.DecodeCanvasSampledSeq(seqs[a], canvas[a], scTok, scPrb, scUse, tempInv, u, K,
                                dArg[a], entropy, dSamp[a], dTopTok[a][dBuf[a]], dTopPrb[a][dBuf[a]]);
                            if (ok)
                            {
                                bool seqDone = DenoiseStepFromDevice(dArg[a], entropy, dSamp[a], renoise, run.Params,
                                    canvas[a], argmaxCanvas[a], prevArgmax[a], ref held[a], order, width[a]);
                                dBuf[a] ^= 1;
                                prevTempInv[a] = tempInv;
                                stepsRun[a]++;
                                run.EmitPreview(stepIdx, S, argmaxCanvas[a]);
                                if (seqDone) { finished[a] = true; converged[a] = true; }
                                continue;
                            }
                            useDeviceSample = false;   // kernel rejected: fall back to the host path for the rest
                            WarnDeviceSampleFallback();
                        }

                        float[] lg;
                        if (usePkv)
                        {
                            lg = _model.DecodeCanvasSeq(seqs[a], canvas[a], scBuffer[a], scUse, prevTempInv[a]);
                        }
                        else
                        {
                            Array.Copy(canvas[a], 0, unifiedTokens[a], promptLen[a], C);
                            lg = _model.ForwardCanvas(unifiedTokens[a], promptLen[a], scBuffer[a], scUse, prevTempInv[a]);
                        }
                        if (scBuffer[a] != null) Array.Copy(lg, scBuffer[a], (long)C * vocab);
                        bool seqFinished = DenoiseStep(lg, tempInv, rng[a], run.Params,
                            canvas[a], argmaxCanvas[a], prevArgmax[a], ref held[a], entropy, denoiser, order, u,
                            renoise, width[a]);
                        prevTempInv[a] = tempInv;
                        stepsRun[a]++;
                        // Only the step that emits is reported, so the top-K sweep runs once per read.
                        if (wantLogprobs[a] && (seqFinished || stepsRun[a] >= S))
                            logprobs[a] = DiffusionLogprobs.TopKPerPosition(
                                lg, width[a], vocab, run.Params.TopLogprobs);
                        run.EmitPreview(stepIdx, S, argmaxCanvas[a]);
                        if (seqFinished) { finished[a] = true; converged[a] = true; }
                    }
                }

                // A request's step cap is its own: once it has run its steps it leaves the batch, even
                // though a longer-running sequence keeps the block going. Without this a read capped at
                // one step would go on denoising to the batch's maximum and emit a canvas it never asked
                // for - and, past its cap, on a temperature schedule that has run off its end.
                foreach (int a in live)
                {
                    if (stepsRun[a] >= Math.Max(1, active[a].Params.MaxDenoisingSteps)) finished[a] = true;
                }

                // retire converged sequences from the batch for the remaining steps
                live.RemoveAll(a => finished[a]);
            }

            // commit each sequence's block: trimmed for a generation, whole for a read (the canvas IS the
            // answer there, so an end-of-turn token drawn into a noise slot must not cut it short).
            for (int a = 0; a < A; a++)
            {
                int W = width[a];
                bool readOnly = active[a].Params.ReadOnly;
                int cut = readOnly ? W : TrimCanvas(argmaxCanvas[a], W);
                var blockTokens = new List<int>(cut);
                for (int i = 0; i < cut; i++) blockTokens.Add(argmaxCanvas[a][i]);
                if (readOnly)
                    active[a].SetReadResult(new DiffusionReadResult(
                        (int[])argmaxCanvas[a].Clone(), logprobs[a], stepsRun[a], converged[a]));
                active[a].CommitBlock(blockTokens, ended: readOnly || cut < W);
            }
        }

        /// <summary>Trim a denoised canvas at the first end-of-generation token, or at the onset of a
        /// repetition loop (a token recurring at stride 1-2 for >= 6 steps).</summary>
        private int TrimCanvas(int[] canvas, int n)
        {
            int cut = n;
            for (int i = 0; i < n; i++)
            {
                if (_model.Tokenizer.IsEos(canvas[i])) { cut = i; break; }
            }
            for (int i = 0; i + 1 < cut; i++)
            {
                bool loop = false;
                for (int stride = 1; stride <= 2 && !loop; stride++)
                {
                    int reps = 0;
                    for (int j = i; j + stride < n && canvas[j] == canvas[j + stride]; j += stride) reps++;
                    if (reps >= 6) loop = true;
                }
                if (loop) { cut = i; break; }
            }
            return cut;
        }

        /// <summary>Small deterministic PRNG (splitmix64 + xorshift) so generation is reproducible
        /// for a given seed independent of the BCL's Random implementation.</summary>
        private sealed class DeterministicRng
        {
            private ulong _state;
            public DeterministicRng(ulong seed)
            {
                // splitmix64 seeding
                _state = seed == 0 ? 0x9E3779B97F4A7C15UL : seed;
            }

            private ulong NextU64()
            {
                ulong z = (_state += 0x9E3779B97F4A7C15UL);
                z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9UL;
                z = (z ^ (z >> 27)) * 0x94D049BB133111EBUL;
                return z ^ (z >> 31);
            }

            public float NextFloat()
            {
                // 24-bit mantissa in [0,1)
                return (NextU64() >> 40) * (1.0f / 16777216.0f);
            }

            public int NextInt(int bound)
            {
                return (int)(NextU64() % (ulong)bound);
            }
        }
    }

    /// <summary>One in-flight request in a batched diffusion generation. Carries the request's params, its
    /// per-sequence model K/V state, the growing prefix (prompt + committed blocks) fed to each block's
    /// prefill, the committed response tokens, and a preview callback. The scheduler drives a set of these
    /// through <see cref="DiffusionGemmaSampler.RunBlockBatched"/> one block at a time; <see cref="Done"/>
    /// flips true when the request ends (end token / repetition) or exhausts its block budget.</summary>
    public sealed class DiffusionSeqRun
    {
        public DiffusionEbParams Params { get; }
        public DiffusionSeqState State { get; }
        public List<int> Prefix { get; }
        public List<int> Response { get; }
        public int BlockIndex { get; private set; }
        public bool Done { get; private set; }
        public CancellationToken Ct { get; }

        /// <summary>The structured read this request produced, set once its read-only block has been
        /// denoised. Null for an ordinary generation.</summary>
        public DiffusionReadResult ReadResult { get; private set; }

        private readonly Action<DiffusionSeqRun, int, int, int[]> _onPreview;   // (run, step, totalSteps, previewTokens)

        public DiffusionSeqRun(int[] promptTokens, DiffusionEbParams p, DiffusionSeqState state,
            CancellationToken ct, Action<DiffusionSeqRun, int, int, int[]> onPreview)
        {
            Params = p;
            State = state;
            Ct = ct;
            _onPreview = onPreview;
            Prefix = new List<int>(promptTokens);
            Response = new List<int>();
        }

        /// <summary>Report the current best-guess (committed response + this block's argmax canvas) to the
        /// preview consumer. Whole-message "replace" semantics, matching the single-request preview.</summary>
        internal void EmitPreview(int step, int totalSteps, int[] argmaxCanvas)
        {
            if (_onPreview == null) return;
            var preview = new int[Response.Count + argmaxCanvas.Length];
            Response.CopyTo(preview, 0);
            argmaxCanvas.CopyTo(preview, Response.Count);
            _onPreview(this, step, totalSteps, preview);
        }

        /// <summary>Commit this block's trimmed tokens. If the block ended (end token / repetition) or this
        /// was the last permitted block, the request is done; otherwise the tokens extend the prefix and the
        /// next block is generated.</summary>
        internal void SetReadResult(DiffusionReadResult result) => ReadResult = result;

        internal void CommitBlock(List<int> blockTokens, bool ended)
        {
            Response.AddRange(blockTokens);
            if (ended || BlockIndex + 1 >= Math.Max(1, Params.MaxBlocks))
                Done = true;
            else
            {
                Prefix.AddRange(blockTokens);
                BlockIndex++;
            }
        }
    }
}
